[package]
name = "Super_ASCII_Bros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-control-codes = "0.0.2"
itertools = "0.11.0"
nix = "0.27.1"
once_cell = "1.18.0"
signal-hook = "0.3.17"
