[package]
name = "super_ascii_bros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
fnv = "1.0.7"
itertools = "0.11.0"
mpsc = "0.2.3"
